### ISSUE TITLE
No tests regarding QuoteCards

### ISSUE THREAD

**Issue by gac2117** [learn-co-curriculum/quote-maker-react-lab#11]
I was coding based on tests and test results and passed all of them. But then when I ran `npm start` to see what this app works like, it wasn't displaying the quotes I added. And then I noticed that I never coded the `QuoteCard` part of the lab. I later discovered it written in the lab README, but maybe it should also be included in the tests.

**Comment by maxwellbenton** [comment]
Hi @gac2117,

Thank you for providing this feedback. We've updated this lab to include tests for `QuoteCard`. We've also added some final tests to ensure that QuoteCard is properly connected to the Redux store and is updating the store through its buttons, which should resolve this issue for future students.

Thank you for contributing!
