### ISSUE TITLE
Reducers in the solution branch are modifying state rather than returning new state

### ISSUE THREAD

**Issue by Sillhouette** [learn-co-curriculum/quote-maker-react-lab#22]
If I'm not mistaken it seems to me like the solution's reducers are modifying state and my understanding is that that is a big `nono`. If this is in fact the case then the solutions should be refactored to return a new state which is the conventions for modifying state in React/Redux

If you would like me to attempt a fix please let me know and I'll look into it

@rrcobb @maxwellbenton

**Comment by rrcobb** [comment]
As far as I can tell, the solution branch is fine as-is.

JS array `concat` and `filter` return new arrays non-destructively, and the quote upvote and downvote features create new arrays. 

What part of the state is being modified?

**Comment by Sillhouette** [comment]
I see, I thought concat was just an alias for push but I did some more reading and you're absolutely correct. Apologies, I'll close this now 👍

**Comment by rrcobb** [comment]
Thanks for opening the issue! It may still be nice to use something that's more obviously non-destructive - not everyone will remember how `concat` works - I had to check it in the console myself!

**Comment by Sillhouette** [comment]
Maybe add something to make it more clear? A comment would probably do just fine to be honest.
