### ISSUE TITLE
Lesson Placement

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/quote-maker-react-lab#26]
I think this lesson should come after the Redux Delete lessons, since deleting a component with Redux (which is required in this lab) hasn't been covered up to this point in the curriculum.

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback. The materials have been updated to address this so I'm closing the issue. 

Thanks for contributing to the Flatiron School curriculum! 💙
