### ISSUE TITLE
Tests a bit wonky

### ISSUE THREAD

**Issue by howardbdev** [learn-co-curriculum/quote-maker-react-lab#5]
Running `learn` command doesn't work (neither does `mocha`).. have to use `npm test`, which is fine, but seems to hang and have to use ctrl + C to end the test run each time.

Running `learn` returns '0 tests passing', which actually returns a green light to the lab page, so moving on is no problem.

**Comment by Lukeghenco** [comment]
Thanks @howardbdev this should be fixed now.
