### ISSUE TITLE
Redundant 'export' keywords in app files

### ISSUE THREAD

**Issue by dtow55** [learn-co-curriculum/quote-maker-react-lab#7]
In the Github code I cloned for this lab, there were several instances where a class is exported twice. For example, class QuoteForm was exported both where it was defined, as well as with an 'export default' statement afterwards: 

**export** class QuoteForm extends Component {
     ... code ... 
}
**export** default connect(null, {})(QuoteForm);

This created a lot of problems for me (and even a coach helping me). I think most students will assume this initially-provided code is bug-free and will be reluctant to remove code unless told in the instructions. I suggest either correct these 'double exports' or mention in the instructions that students will need to remove/change export statements.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials, removed the extra exports from this lab and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
