### ISSUE TITLE
'npm start' command won't work

### ISSUE THREAD

**Issue by BuffaloRob** [learn-co-curriculum/quote-maker-react-lab#8]
I got it to work by removing and re-installing webpack:
1) npm remove webpack
2) npm install webpack@3.11.0

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials including the package versions and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
