### ISSUE TITLE
Lab incorrectly placed in V6?

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/quote-maker-react-lab#9]
There are a lot of things necessary for this lab that are covered in the two codealongs at the beginning of the next section.

**Comment by ddhogan** [comment]
omg thank you for raising this issue!

**Comment by lizbur10** [comment]
There’s more later in the next section as well but I don’t remember where. I meant to come back and update this issue but I didn’t get around to it

**Comment by maxwellbenton** [comment]
Hi @lizbur10,

Thanks for reporting this issue. We're now aware of it and are tracking this and other ordering issues in a new issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3). 

We are currently updating and restructuring the materials in this section and will add this to our internal work queue.  We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
